import { APP_PREFIX_PATH } from "@/constants/route.constant";
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "@/constants/navigation.constant";
import { USER, OWNER, SELLER_FIXED } from "@/constants/roles.constant";
import type { NavigationTree } from "@/@types/navigation";

const appsNavigationConfig: NavigationTree[] = [
  {
    key: "apps",
    path: "",
    title: "APPS",
    translateKey: "nav.apps",
    icon: "apps",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [OWNER, SELLER_FIXED],
    subMenu: [
      {
        key: "apps.inventory",
        path: "",
        title: "Organizar Inventario",
        translateKey: "nav.appsCrm.org",
        icon: "knowledgeBase",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
          {
            key: "appsSales.currency",
            path: `${APP_PREFIX_PATH}/accounting/Currency`,
            title: "Divisa",
            translateKey: "nav.appsSales.currency",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.categoryList",
            path: `${APP_PREFIX_PATH}/sales/categories`,
            title: "Categorias",
            translateKey: "nav.appsSales.categoryList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.attributeNew",
            path: `${APP_PREFIX_PATH}/sales/attribute-new`,
            title: "Nuevo Atributo",
            translateKey: "nav.appsSales.attributeNew",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.supplies",
        path: "",
        title: "Insumo",
        translateKey: "nav.appsCrm.supply",
        icon: "knowledgeBase",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
          {
            key: "appsSales.supplyNew",
            path: `${APP_PREFIX_PATH}/sales/supply-new`,
            title: "Crear Insumo",
            translateKey: "nav.appsSales.supplyNew",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.supplyList",
            path: `${APP_PREFIX_PATH}/sales/supplies`,
            title: "Lista de Insumos",
            translateKey: "nav.appsSales.supplyList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.catalog",
        path: "",
        title: "Catalogo",
        translateKey: "nav.appsCrm.catalog",
        icon: "inventory",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
          {
            key: "appsSales.sections",
            path: `${APP_PREFIX_PATH}/catalog`,
            title: "Secciones",
            translateKey: "nav.appsSales.catalog",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.slides",
            path: `${APP_PREFIX_PATH}/slides`,
            title: "Diapositivas",
            translateKey: "nav.appsSales.catalog",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.Cslides",
            path: `${APP_PREFIX_PATH}/Cslides`,
            title: "Crear Diapositivas",
            translateKey: "nav.appsSales.catalog",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },

          {
            key: "appsSales.offerForm",
            path: `${APP_PREFIX_PATH}/sales/createForm`,
            title: "Crear Oferta",
            translateKey: "nav.appsSales.offerForm",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.offerTable",
            path: `${APP_PREFIX_PATH}/sales/offerTable`,
            title: "Tabla de Ofertas",
            translateKey: "nav.appsSales.offerTable",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.crm",
        path: "",
        title: "CRM",
        translateKey: "nav.appsCrm.crm",
        icon: "inventory",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, SELLER_FIXED],
        subMenu: [
          {
            key: "appsSales.productList",
            path: `${APP_PREFIX_PATH}/sales/product-list`,
            title: "Product List",
            translateKey: "nav.appsSales.productList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.delivery",
            path: `${APP_PREFIX_PATH}/sales/delivery`,
            title: "Mensajería",
            translateKey: "nav.appsSales.delivery",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          /* {
            key: "appsSales.orderList",
            path: `${APP_PREFIX_PATH}/sales/orders`,
            title: "Lista de Orden",
            translateKey: "nav.appsSales.orderList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [SELLER_FIXED],
            subMenu: [],
          }, */
          {
            key: "appsSales.productNew",
            path: `${APP_PREFIX_PATH}/sales/product-new`,
            title: "New Product",
            translateKey: "nav.appsSales.productNew",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.sellerCatalog",
            path: `${APP_PREFIX_PATH}/sales/sellerCatalog`,
            title: "Crear Orden",
            translateKey: "nav.appsSales.sellerCatalog",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [SELLER_FIXED],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.customers",
        path: "",
        title: "Vendedores",
        translateKey: "nav.appsSales.customers",
        icon: "sales",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, SELLER_FIXED],
        subMenu: [
          {
            key: "appsSales.clients",
            path: `${APP_PREFIX_PATH}/sales/clients`,
            title: "Tus Clientes",
            translateKey: "nav.appsSales.clients",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [SELLER_FIXED],
            subMenu: [],
          },
          {
            key: "appsSales.leaderboardSellers",
            path: `${APP_PREFIX_PATH}/sales/leaderboardSellers`,
            title: "Tabla Insigna",
            translateKey: "nav.appsSales.leaderboardSellers",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER, SELLER_FIXED],
            subMenu: [],
          },
          /* {
            key: "appsSales.sellerList",
            path: `${APP_PREFIX_PATH}/sales/sellers`,
            title: "Lista de Vendedores",
            translateKey: "nav.appsSales.sellerList",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          }, */
        ],
      },
      {
        key: "apps.account",
        path: "",
        title: "Cuenta",
        translateKey: "nav.appsAccount.account",
        icon: "account",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
          {
            key: "appsAccount.settings",
            path: `${APP_PREFIX_PATH}/account/settings/profile`,
            title: "Configuración",
            translateKey: "nav.appsAccount.settings",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "apps.sales",
        path: "",
        title: "Ventas",
        translateKey: "nav.appsSales.sales",
        icon: "sales",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
          {
            key: "appsSales.dashboard",
            path: `${APP_PREFIX_PATH}/sales/dashboard`,
            title: "Dashboard",
            translateKey: "nav.appsSales.dashboard",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          },
          {
            key: "appsSales.profit",
            path: `${APP_PREFIX_PATH}/sales/profit`,
            title: "Beneficio",
            translateKey: "nav.appsSales.profit",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          } /* 
          {
            key: "appsSales.orderDetails",
            path: `${APP_PREFIX_PATH}/sales/order-details/95954`,
            title: "Order Details",
            translateKey: "nav.appsSales.orderDetails",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [OWNER],
            subMenu: [],
          }, */,
        ],
      },
    ],
  },
];

export default appsNavigationConfig; /* {
/* 

{
                key: 'apps.project',
                path: '',
                title: 'Project',
                translateKey: 'nav.appsProject.project',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [OWNER, USER],
                subMenu: [
                    {
                        key: 'appsProject.dashboard',
                        path: `${APP_PREFIX_PATH}/project/dashboard`,
                        title: 'Dashboard',
                        translateKey: 'nav.appsProject.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProject.projectList',
                        path: `${APP_PREFIX_PATH}/project/project-list`,
                        title: 'Project List',
                        translateKey: 'nav.appsProject.projectList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProject.scrumBoard',
                        path: `${APP_PREFIX_PATH}/project/scrum-board`,
                        title: 'Scrum Board',
                        translateKey: 'nav.appsProject.scrumBoard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProject.issue',
                        path: `${APP_PREFIX_PATH}/project/issue`,
                        title: 'Issue',
                        translateKey: 'nav.appsProject.issue',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                ],
            }, */

/* */

/*  {
                key: 'apps.crypto',
                path: '',
                title: 'Crypto',
                translateKey: 'nav.appsCrypto.crypto',
                icon: 'crypto',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [OWNER, USER],
                subMenu: [
                    {
                        key: 'appsCrypto.dashboard',
                        path: `${APP_PREFIX_PATH}/crypto/dashboard`,
                        title: 'Dashboard',
                        translateKey: 'nav.appsCrypto.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCrypto.portfolio',
                        path: `${APP_PREFIX_PATH}/crypto/portfolio`,
                        title: 'Portfolio',
                        translateKey: 'nav.appsCrypto.portfolio',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCrypto.market',
                        path: `${APP_PREFIX_PATH}/crypto/market`,
                        title: 'Market',
                        translateKey: 'nav.appsCrypto.market',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCrypto.wallets',
                        path: `${APP_PREFIX_PATH}/crypto/wallets`,
                        title: 'Wallets',
                        translateKey: 'nav.appsCrypto.wallets',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                ],
            }, */
/*  {
                key: 'apps.knowledgeBase',
                path: '',
                title: 'Knowledge Base',
                translateKey: 'nav.appsknowledgeBase.knowledgeBase',
                icon: 'knowledgeBase',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [OWNER, USER],
                subMenu: [
                    {
                        key: 'appsknowledgeBase.helpCenter',
                        path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
                        title: 'Help Center',
                        translateKey: 'nav.appsknowledgeBase.helpCenter',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.article',
                        path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
                        title: 'Article',
                        translateKey: 'nav.appsknowledgeBase.article',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.manageArticles',
                        path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
                        title: 'Manage Articles',
                        translateKey: 'nav.appsknowledgeBase.manageArticles',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.editArticle',
                        path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
                        title: 'Edit Article',
                        translateKey: 'nav.appsknowledgeBase.editArticle',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                ],
            }, {
                        key: 'appsAccount.invoice',
                        path: `${APP_PREFIX_PATH}/account/invoice/36223`,
                        title: 'Invoice',
                        translateKey: 'nav.appsAccount.invoice',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.activityLog',
                        path: `${APP_PREFIX_PATH}/account/activity-log`,
                        title: 'Activity Log',
                        translateKey: 'nav.appsAccount.activityLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.kycForm',
                        path: `${APP_PREFIX_PATH}/account/kyc-form`,
                        title: 'KYC Form',
                        translateKey: 'nav.appsAccount.kycForm',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [OWNER, USER],
                        subMenu: [],
                    }, */
